import type { AWS } from "@serverless/typescript";
const CognitoResources: AWS["resources"]["Resources"] = {
  CognitoUserPool: {
    Type: "AWS::Cognito::UserPool",
    Properties: {
      UserPoolName: "${sls:stage}-${self:service}-user-pool",
      UsernameAttributes: ["email"],
      AutoVerifiedAttributes: ["email"],
      Policies: {
        PasswordPolicy: {
          MinimumLength: 8,
          RequireLowercase: false,
          RequireNumbers: false,
          RequireUppercase: false,
          RequireSymbols: false,
        },
      },
    },
  },

  CognitoUserPoolClient: {
    Type: "AWS::Cognito::UserPoolClient",
    Properties: {
      ClientName: "${sls:stage}-${self:service}-user-pool-client",
      UserPoolId: { Ref: "CognitoUserPool" },
      CallbackURLs: [
        "http://localhost:3000/api/auth/callback/cognito",
        "https://serverless-todo-app-mu.vercel.app/api/auth/callback/cognito",
      ],
      ExplicitAuthFlows: [
        "ALLOW_REFRESH_TOKEN_AUTH",
        "ALLOW_USER_SRP_AUTH",
        "ALLOW_USER_PASSWORD_AUTH",
      ],
      AuthSessionValidity: 3,
      RefreshTokenValidity: 30,
      AccessTokenValidity: 60,
      IdTokenValidity: 60,
      TokenValidityUnits: {
        RefreshToken: "days",
        AccessToken: "minutes",
        IdToken: "minutes",
      },
      EnableTokenRevocation: true,
      PreventUserExistenceErrors: "ENABLED",
      AllowedOAuthFlows: ["code"],
      AllowedOAuthScopes: ["openid", "phone", "email"],
      SupportedIdentityProviders: ["COGNITO"],
      AllowedOAuthFlowsUserPoolClient: true,
      GenerateSecret: true,
      ReadAttributes: [
        "address",
        "birthdate",
        "email",
        "email_verified",
        "family_name",
        "gender",
        "given_name",
        "locale",
        "middle_name",
        "name",
        "nickname",
        "phone_number",
        "phone_number_verified",
        "picture",
        "preferred_username",
        "profile",
        "updated_at",
        "website",
        "zoneinfo",
      ],
      WriteAttributes: [
        "address",
        "birthdate",
        "email",
        "family_name",
        "gender",
        "given_name",
        "locale",
        "middle_name",
        "name",
        "nickname",
        "phone_number",
        "picture",
        "preferred_username",
        "profile",
        "updated_at",
        "website",
        "zoneinfo",
      ],
    },
  },

  CognitoUserPoolDomain: {
    Type: "AWS::Cognito::UserPoolDomain",
    Properties: {
      Domain: "${sls:stage}-${self:service}",
      UserPoolId: { Ref: "CognitoUserPool" },
    },
  },
};
export default CognitoResources;
