import "./globals.css";
import awsExports from "../../aws-exports";
import { Amplify } from "aws-amplify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure({
  Auth: {
      region: awsExports.REGION,
      userPoolId: awsExports.USER_POOL_ID,
      userPoolWebClientId: awsExports.USER_POOL_APP_CLIENT_ID
  }
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
